package template;

import java.util.List;

/**
 * Concrete template for JSON configuration files.
 */
public class JsonTemplate extends Template {

    @Override
    protected List<String> generateHeader(String fileName) {
        return List.of("{");
    }

    @Override
    protected List<String> generateBody(String fileName) {
        return List.of(
                "  \"name\": \"" + fileName + "\",",
                "  \"version\": \"1.0.0\",",
                "  \"description\": \"Configuration generated by Console File Editor\",",
                "  \"settings\": {",
                "    \"enabled\": true,",
                "    \"maxRetries\": 3",
                "  }"
        );
    }

    @Override
    protected List<String> generateFooter(String fileName) {
        return List.of("}");
    }

    @Override
    public String getTemplateType() {
        return "JSON Configuration";
    }

    @Override
    public String getDefaultExtension() {
        return "json";
    }
}
