package template;

import java.util.List;

/**
 * Concrete template for Markdown documentation files.
 */
public class MarkdownTemplate extends Template {

    @Override
    protected List<String> generateHeader(String fileName) {
        String title = fileName.replaceAll("(?i)\\.md$", "");
        return List.of(
                "# " + title,
                "",
                "> Initial documentation scaffold.",
                ""
        );
    }

    @Override
    protected List<String> generateBody(String fileName) {
        return List.of(
                "## Overview",
                "Describe the purpose of this document here.",
                "",
                "## Getting Started",
                "- Step 1: Initialize project",
                "- Step 2: Run tests",
                "",
                "## Notes",
                "- TODO: Add detailed specification."
        );
    }

    @Override
    protected List<String> generateFooter(String fileName) {
        return List.of(
                "",
                "---",
                "*Generated by Console File Editor*"
        );
    }

    @Override
    public String getTemplateType() {
        return "Markdown Document";
    }

    @Override
    public String getDefaultExtension() {
        return "md";
    }
}
